# -*- coding: utf-8 -*-
# Part of Odoo. See LICENSE file for full copyright and licensing details.

from odoo import api, fields, models, _
from odoo.exceptions import AccessError, UserError


class BaseConfigSettings(models.TransientModel):
    _inherit = "base.config.settings"

    default_sms_provider_id = fields.Many2one(
        'sms.provider', string='Default SMS Provider',
        help="By default, SMS text messages generated by Odoo will use this provider.")

    def set_default_sms_provider_id(self):
        if not self.user_has_groups('base.group_system'):
            raise AccessError(_('Settings access rights are required to change this configuration.'))
        Param = self.env['ir.config_parameter'].sudo()
        Param.set_param("default_sms_provider_id", self.default_sms_provider_id.id)

    @api.model
    def get_default_sms_provider_id(self, fields):
        if not self.user_has_groups('base.group_system'):
            raise AccessError(_('Settings access rights are required to access this.'))
        Param = self.env['ir.config_parameter'].sudo()
        return {'default_sms_provider_id': Param.get_param('default_sms_provider_id', default=False)}

    def action_sms_test(self):
        if not self.default_sms_provider_id:
            raise UserError(_('Please set a default SMS provider.'))
        self.default_sms_provider_id._test_sms()
